####################################################
#                                                  #
#                  SONOFF SALON                    #
#                                                  #
####################################################
- platform: mqtt
  name: "On/Off Sonoff Salón"
  state_topic: "tele/salon/STATE"
  value_template: '{{ value_json["POWER1"] }}'
  command_topic: "cmnd/salon/POWER"
  availability_topic: "tele/salon/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

####################################################
#                                                  #
#                SONOFF Rodrigo                    #
#                                                  #
####################################################
- platform: mqtt
  name: "On/Off Sonoff Rodrigo"
  state_topic: "tele/rodrigo/STATE"
  value_template: '{{ value_json["POWER1"] }}'
  command_topic: "cmnd/rodrigo/POWER"
  availability_topic: "tele/rodrigo/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
