####################################################
#                                                  #
#                 CAMERA RODRIGO                   #
#                                                  #
####################################################

- platform: ffmpeg
  name: Rodrigo Camera
  input: rtsp://192.168.25.191:554/unicast